name: CI TacoExpress

on:
  push:
    branches:
      - main
      - develop

  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Obtener codigo
        uses: actions/checkout@v4

      - name: Configurar Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Crear archivos Android
        run: flutter create --platforms=android .

      - name: Instalar dependencias
        run: flutter pub get

      - name: Analizar codigo
        run: flutter analyze

      - name: Ejecutar pruebas
        run: flutter test

      - name: Generar APK
        run: flutter build apk --release

      - name: Renombrar APK
        run: cp build/app/outputs/flutter-apk/app-release.apk TacoExpress.apk

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: TacoExpress-APK
          path: TacoExpress.apk

      - name: Construir imagen Docker
        run: docker build -t tacoexpress:latest .

      - name: Verificar imagen Docker
        run: docker images
